### PR TITLE
Added Polish translation

### PR DESCRIPTION
**Pull request by einsteinsfool**
Sometimes I was more detailed in my translation than in the original text. Let me know if there are phrases that are too long.

Also, I didn't quite get "Payment ID 8". What does the 8 refer to?

### CODE REVIEW

**Comment by Equim-chan** [comment]
I think "8" here means the Payment ID is 8 bytes long, and is encrypted, usually a result of integrated address.

**Comment by GBKS** [comment]
Thank you for the translation. I will add it to the site and then we can test and see how the length works out. I might also need to adjust the design if text ends up looking goofy in translations. There were definitely a few places where I picked font sizes so the text looks good in English.

I also wasn't sure about the 8. The data I get from the API has a "payment_id" and a "payment_id_8". I couldn't find any documentation on this anywhere so I simply included the 8, hoping that somebody would bring it up and clarify (thank you). But sounds like we can just remove that.

Is "Polskie" the right label for the language selector?

**Comment by einsteinsfool** [comment]
Thanks, @Equim-chan. Changed the translation to mean "8-byte payment ID".

@GBKS You're welcome. I think you can leave the 8-byte ID in case somebody needs it. I'd just change the phrase to the one above or to "Compressed 8-byte payment ID".

It should by "Polski". :-) Suggested an improvement on Google Translate.

**Comment by GBKS** [comment]
Thank you, adding it to the site in the next few minutes. Also adding your Github name and link to the list of translation contributors on the about page (unless you prefer me not to, or prefer some other name/link).

**Pull request merged**
