### PR TITLE
Add Chinese Simplified translation.

### PR DESCRIPTION
**Pull request by Equim-chan**
Nice work and good luck! 😃

### CODE REVIEW

**Comment by GBKS** [comment]
Thank you. What would be the right label for this in the language selector? I'd like for those labels to be in the language itself (e.g. "Deutsch" instead of "German").

Are you aware of anything that needs to be considered for rendering Chinese characters/content? I'm using default system fonts, but there might still be some other differences that I'm now aware of.

**Comment by Equim-chan** [comment]
The label should be "简体中文".

I'll check the rendering when it gets live.

**Comment by GBKS** [comment]
It's live now. Everything looks good on my MacBook.

I also added a list of localization contributors to the about page, and will do the same in the readme file for this Github repo. Your name links to your Github profile, but let me know if you'd like me to change that. Is that good with you?

**Comment by Equim-chan** [comment]
It looks fine, thanks.

**Pull request merged**
