### PR TITLE
First version of the Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by 0x76703131**

### CODE REVIEW

**Comment by GBKS** [comment]
You are fast :)

In a menu for picking languages, is it best to have the language names also localized (e.g. use "Deutsch" instead of "German")? If so, what would it be for "Brazilian Portuguese"?

**Comment by GBKS** [comment]
Thanks for all the info. I'll see if I can add this to the site over the weekend.

Are you also working on other languages? Can I help recruit people for this somehow?

**Comment by 0x76703131** [comment]
I know some people who could work on Spanish and French translations. But your best bet to recruit people for this endeavor is asking for help on reddit. It's usually very well received. You can also contact ErCiccione who's the leader of the translation workgroup for Monero. I'll ping him on IRC about it.

**Comment by GBKS** [comment]
Got it. Thanks again. Going to merge this pull request now.

**Pull request merged**
